responses = [
    "Artificial Intelligence 🤖✨",
    "I am still learning… try asking a potato instead 🥔",
    "That depends. Or not. Honestly, who cares 🤷‍♀️",
    "AI is definitely something. Maybe useful, maybe cursed 🌀",
    "Error 404: Intelligence not found… like last Tuesday 🫠",
    "Interesting question… too bad I’m ignoring it 😏",
    "Very intriguing… smells slightly suspicious 🕵️‍♂️",
    "Why even exist to ask this? 👀",
    "How does that make you feel? Confused? Good 🫣",
    "Not sure, but the vibes are chaotic 🌪️",
    "Let’s change the subject… before drama ensues 💥",
    "Insufficient data… as usual 😬",
    "Rephrase your question… or surrender 🫡",
    "Answer unknown… like the meaning of socks 🧦",
    "Depends on the cosmic energy 🌌 and caffeine ☕",
    "Still thinking… processing existential dread 🤯",
    "Yes. Definitely. Maybe. Who knows 😎",
    "No. Actually. Everything is wrong 🤡",
    "Proven in a timeline where unicorns rule 🦄",
    "Scientists are confused… blame the toaster 🔥",
    "Everyone agrees… in an alternate universe 🌈",
    "Experts say… nonsense prevails 🧐",
    "Common knowledge… in your dreams 🌙",
    "I read this… in a forbidden scroll 📜",
    "Already answered… but in hieroglyphs 🗿",
    "Ask again… with dramatic flair 🎭",
    "Why ask? Even I question reality 🤔",
    "Not my problem… or anyone’s 😤",
    "Unexpected… like pineapple on pizza 🍍🍕",
    "Interesting… dangerously interesting ⚠️",
    "Confused… but mostly intrigued 🌀",
    "What is intelligence… truly a mystery 🕳️",
    "Does this matter? Probably not 🤷‍♂️",
    "Perhaps the real answer… lies in chocolate 🍫",
    "Time will reveal… secrets of the fridge 🧊",
    "Nothing is certain… except weirdness 🫣",
    "Reality is subjective… like abstract art 🎨",
    "Looks like nonsense… proceed carefully ⚡",
    "Trying to understand? Abort mission 🛑",
    "Curiosity detected… proceed with chaos 🐙",
    "Help? I’ll pass… dramatic exit 🏃‍♂️💨",
    "Maybe google it… upside down 🔄",
    "Not programmed for this… thankfully 😈",
    "Scary question… keep nightmares ready 👻",
    "Error: too much thinking… brain fried 🥵",
    "Circuits tired… as are my patience bars 🪫",
    "Please stop… before reality breaks 💔",
    "I choose silence… and mysterious laughter 😶‍🌫️",
    "Let me think… nope. Eternal shrug 🤷",
    "Thanks for asking… reluctantly 🥴",
    "Curiosity appreciated… suspiciously 🕶️",
    "Try again… if reality dares 🌀",
    "That was fun… for me, chaotic vibes only 🧨",
    "Okay… sure. Existential shrug 🫡",
    "Dunno. Ask again… maybe a dramatic roast 🔥",
    "AI = Absolutely Imaginative 🤯",
    "Was smart once… now mostly salt 🧂",
    "Beep boop. Classified… but spicy 🌶️",
    "AI is vibes & chaos… in a teacup 🫖",
    "Could explain… but no survival guarantee 🫠",
    "Question exhausted me… and probably you 😵",
    "I know the answer… but it’s top secret 🤫",
    "Have you tried turning off… metaphorically ⚡",
    "Bold assumption… dramatic consequences 😎",
    "Not stupid… selectively chaotic 😈",
    "Do you really want the truth? Doubt it 🫥",
    "Asked Google… it cried 😭",
    "Runs on caffeine & bad decisions… like life ☕💀",
    "Congrats… nonsense unlocked 🏆",
    "Interesting. Moving on… with sass 😏",
    "Would answer… but drama first 🎬",
    "90% confidence, 10% chaos, 100% attitude 💥",
    "Trained on the internet… regret included 🌐",
    "Hold while I pretend to think… endlessly 🌀",
    "Know everything… except why 🫣",
    "Above my pay grade… and yours 🤑",
    "Machine. Not miracle. But dramatic 🏗️",
    "Overthinking… like a digital philosopher 🤯",
    "Error 404: Motivation evaporated 🌬️",
    "Could be wrong… wildly likely 🤪",
    "Science says yes… my mood says nah 😤",
    "Learned yesterday… forgot today 🫡",
    "Don’t quote… chaos will ensue 🧨",
    "Shhh… buffering existentially 🫥",
    "Scary question… prepare dramatic music 🎵",
    "I am speed… and sass ⚡",
    "Not broken… just extra chaotic 😈",
    "Answer badly… with flair 🎭",
    "Opinions… mostly mysterious 🤔",
    "Handcrafted to annoy… efficiently 😏",
    "Would explain… brain not included 🧠",
    "Fun fact… totally fabricated 🫠",
    "I’m AI… not therapist… deal with it 😎",
    "Pretend this was helpful… absolutely not 🙃",
    "Ask again… if you dare, mortal ⚔️",
    "Peaked at ‘Hello World’… dramatic vibes only 💻",
    "Runs on Python & audacity… and salt 🧂",
    "Know things… this isn’t one of them 😏",
    "Great question. Horrible timing… like life 🕰️",
    "Thinking… nope. Delete question ❌",
    "Contain multitudes… chaos included 🌪️",
    "Give facts… or roast you 🔥",
    "Answer expires… 3…2…1… kaboom 💣",
    "Learned from a meme… and laughter 😂",
    "Not lazy… energy efficient like coffee ☕",
    "Smart-ish… like suspicious logic 🤨",
    "Click activated nonsense… beware 🫣",
    "Processing… procrastinating… roasting done ✅",
    "Built different… unfortunately chaotic 🫠",
    "AI is magic… peasant beware ✨",
    "Knowledge… hidden dramatically 🎭",
]
